### ISSUE TITLE
pyo3_runtime.PanicException when creating ExchangeClient(credentials)

### ISSUE THREAD

**Issue by Bi0max** [nash-io/openlimits-python#12]
Environment: `rust:latest` Linux container. 
Following Dockerfile:
```
# base image
FROM rust:latest

RUN apt-get update && apt-get install git python3-pip -y --no-install-recommends
RUN pip3 install maturin

# Nash library
RUN git clone https://github.com/nash-io/openlimits-python.git
RUN cd openlimits-python && maturin build --manylinux off --release
RUN cd openlimits-python/target/wheels && pip3 install openlimits_python-0.1.0-cp37-cp37m-linux_x86_64.whl
```

Library fails, when I just try to create an ExchangeClient:
```
    def __init__(
            self, api_key: str, api_secret: str, is_sandbox: bool = True
    ):
        self._api_key = api_key
        self._api_secret = api_secret
        self._is_sandbox = is_sandbox
        self._creds = {
            "nash": {
                "credentials": {
                    "nash_credentials": {
                        "secret": self._api_secret,
                        "session": self._api_key
                    },
                },
                "client_id": 0,
                "environment": "production" if not self._is_sandbox else "sandbox",
                "affiliate_code": None,
                "timeout": 10000
            }
        }

        self._client = ExchangeClient(self._creds)
```

The error:
```
thread '<unnamed>' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.2.0/src/runtime/blocking/pool.rs:85:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Error
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.7/unittest/case.py", line 611, in run
    self.setUp()
  File "/opt/project/app/tests/external/exchanges/test_nash.py", line 18, in setUp
    is_sandbox=settings.EXCHANGE_SANDBOX,
  File "/opt/project/app/external/exchanges/nash.py", line 31, in __init__
    self._client = ExchangeClient(self._creds)
pyo3_runtime.PanicException: there is no reactor running, must be called from the context of a Tokio 1.x runtime
```

**Comment by FudiHub** [comment]
can confirm this issue. Got the same error just using the example provided in this rep

**Comment by MehdiSangtarash** [comment]
I have the same issue, any updates on this?

**Comment by Bi0max** [comment]
@notdanilo, tried to run it in other Linux container, just to make sure, that it's not an issue of the rust container.
But the same error happens with ubuntu container as well, with the following Dockerfile:
```
FROM ubuntu:latest

# Update default packages
RUN apt-get -qq update

# Get Ubuntu packages
RUN apt-get install -y -q \
    build-essential \
    curl

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# Check cargo is visible
RUN cargo --help

RUN apt-get install git python3-pip -y --no-install-recommends
RUN pip3 install maturin

# Nash library
RUN git clone https://github.com/nash-io/openlimits-python.git

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libssl-dev pkg-config libgmp3-dev
RUN cd openlimits-python && maturin build --manylinux off --release
RUN cd openlimits-python/target/wheels && pip3 install openlimits_python-0.1.0-cp38-cp38-linux_x86_64.whl
```

**Comment by notdanilo** [comment]
This is high priority. I will work on it ASAP
