### ISSUE TITLE
ImportError: DLL load failed while importing openlimits_python

### ISSUE THREAD

**Issue by Bi0max** [nash-io/openlimits-python#13]
I have installed the wheel on Windows 10, but it gives an error, when importing:
```
Error
Traceback (most recent call last):
  File "C:\Users\Maksim\Miniconda3\envs\arb32\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "C:\Users\Maksim\Miniconda3\envs\arb32\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "C:\Users\Maksim\Miniconda3\envs\arb32\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "C:\Users\Maksim\Miniconda3\envs\arb32\lib\unittest\loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_nash
Traceback (most recent call last):
  File "C:\Users\Maksim\Miniconda3\envs\arb32\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "D:\projects\arbitrage_trader\arbitrage_trader\tests\exchange\test_nash.py", line 4, in <module>
    from openlimits_python import ExchangeClient
ImportError: DLL load failed while importing openlimits_python: The specified module could not be found.
```

**Comment by notdanilo** [comment]
@Bi0max have you verified that you have gmp.dll installed?

**Comment by Bi0max** [comment]
@notdanilo, yes, I put it to `C:\Users\XXX\.rustup\toolchains\nightly-i686-pc-windows-msvc\lib\rustlib\i686-pc-windows-msvc\lib`, as described in the link, that you provided here https://github.com/nash-io/openlimits/issues/167. Without putting it there, it would not even compile.
Should I put it somewhere else as well to be able to import the library?

**Comment by notdanilo** [comment]
@Bi0max I just realized this is not related to `gmp.dll`. It is not finding `openlimits_python.dll` produced by `maturin build`.

**Comment by notdanilo** [comment]
@Bi0max fyi I will try to replicate this issue on my Windows machine.
