### ISSUE TITLE
thread '<unnamed>' panicked at 'Tokio runtime shutdown channel had an error: RecvError(())'

### ISSUE THREAD

**Issue by 0000vt** [nash-io/openlimits-python#2]
Hi, on ubuntu I get the following error:

`
thread '<unnamed>' panicked at 'Tokio runtime shutdown channel had an error: RecvError(())', src/lib.rs:77:17
stack backtrace:
`

I managed to build with maturin using --manylinux off

Script:

```  GNU nano 4.8                                                                                       nash.py
from openlimits_python import ExchangeClient
from dotenv import load_dotenv
import os

load_dotenv()

nash_creds = {
    "nash": {
        "credentials": {
            "nash_credentials": {
                "secret": os.getenv("NASH_API_SECRET"),
                "session": os.getenv("NASH_API_KEY")
            },
        },
        "client_id": 0,
        "environment": "production",
        "timeout": 10000
    }
}
client = ExchangeClient(nash_creds)
```

>> uname -a
' Linux python1 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux '

**Comment by notdanilo** [comment]
Hi @0000vt! I am trying to replicate this issue on my machine. This the full message I am getting. Is that the same for you?

```rust
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ProtocolError("Could not connect to WS")', /home/notdanilo/.cargo/git/checkouts/openlimits-83d111e4073e20b4/fefa9c1/src/nash/mod.rs:72:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'Tokio runtime shutdown channel had an error: RecvError(())', src/lib.rs:77:35
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    client = ExchangeClient(nash_creds)
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ProtocolError("Could not connect to WS")
```

**Comment by 0000vt** [comment]
No, it's just the line with Tokio runtime

``` 
xxxx@python1:~/arb/openlimits-python$ python3 bot.py
thread '<unnamed>' panicked at 'Tokio runtime shutdown channel had an error: RecvError(())', src/lib.rs:77:17
stack backtrace:
xxxx@python1:~/arb/openlimits-python$
```
